name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install server deps
        working-directory: server
        run: npm ci

      - name: Install client deps
        working-directory: client
        run: npm ci

      - name: Lint client
        working-directory: client
        run: npm run lint -- --max-warnings=0

      - name: Build client
        working-directory: client
        env:
          VITE_BACKEND_URL: http://localhost:5000/api
          VITE_BACKEND_AUTH_URL: http://localhost:5000/api/auth
          VITE_MAIN_BACKEND_URL: http://localhost:5000/api
          VITE_APP_NAME: WalkUp E-commerce
          VITE_APP_VERSION: 1.0.0
        run: npm run build

      - name: Sanity check server start (no secrets)
        working-directory: server
        env:
          PORT: 5000
          NODE_ENV: test
        run: node -e "console.log('Server files present. Skipping real start in CI.')"


